Forums/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect

def redirect(request):
	return HttpResponseRedirect('/login/')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('Login.urls')),
    url(r'^threads/', include('Threads.urls')), 
    url(r'^.*$', redirect)
]

Login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'Login'
urlpatterns = [
    url(r'^$', views.Login, name='Login'),
 	url(r'^register/', views.Register, name='Register'),
 	url(r'^logout/', views.Logout, name='Logout'),
]

Threads/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'Threads'
urlpatterns = [
	url(r'^$', views.Home, name='Home'),
	url(r'^(?P<id>[0-9])/', views.comment, name='Comment'),	
	url(r'^(?P<username>[a-zA-Z0-9]+)/create/', views.createThread, name='Create'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/', views.Threads, name='Thread'),
]

Login/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class User(User):
	pass

Threads/models.py
from __future__ import unicode_literals

from django.db import models

from Login.models import User

# Create your models here.
class Thread(models.Model):
	id = models.AutoField(primary_key=True)
	text = models.CharField(max_length=2000)
	author = models.ForeignKey(User)

	def __str__(self):
		return self.text

class Comment(models.Model):
	text = models.CharField(max_length=2000)
	author = models.ForeignKey(User)
	thread = models.ForeignKey(Thread)

Login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
from .models import User
def Register(request):
	if request.POST:
		if(request.POST['username'] == ""  or request.POST['fname'] == "" 
			or request.POST['lname'] == "" or request.POST['password'] == ""
			or request.POST["email"] == ""):
			return render(request, 'Login/Register.html', {'fill' : 1})
		try:
			u = User.objects.get(username=request.POST['username'])
			return render(request, 'Login/Register.html', {'username' : 1})
		except:
			pass
		try:
			u = User.objects.get(email=request.POST['email'])
			return render(request, 'Login/Register.html', {'email' : 1})
		except:
			pass
		u = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
		u.first_name = request.POST['fname']
		u.last_name = request.POST['lname']
		u.save()
		return render(request, 'Login/Login.html', {'register' : 1})
	return render(request, 'Login/Register.html')

def Login(request):
	if(request.session.get('logged_in', False)):
		user = User.objects.get(username=request.session['user'])
		return HttpResponseRedirect('/threads/'+request.session['user']+'/')
	if request.POST:
		try:
			user = User.objects.get(username=request.POST['username'])
			if(user.check_password(request.POST['password'])):
				pass
			else:
				return render(request, 'Login/Login.html', {'status' : 1})
		except:
			return render(request, 'Login/Login.html', {'status' : 1})
		request.session['logged_in'] = True
		request.session['user'] = user.username
		return HttpResponseRedirect('/threads/')
	return render(request, 'Login/Login.html')

def Logout(request):
	request.session['logged_in'] = False
	request.session['user'] = None
	return HttpResponseRedirect('/login/')
	
##hjasklgfiulsdkbagfal##

Threads/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from Login.models import User
from .models import Thread, Comment
# Create your views here.
def Home(request):
	if(request.session['logged_in']):
		return HttpResponseRedirect('/threads/'+request.session['user']+'/')
	return HttpResponseRedirect('/login/')

def Threads(request, username):
	#try:
		user = User.objects.get(username=username)
		threadlist = Thread.objects.all()
		if(request.session['logged_in']):
			return render(request, 'Threads/threads.html', {'threadlist' : threadlist, 'User': user,})
		else:
			return HttpResponseRedirect('/login/')
	#except:
	#	return HttpResponseRedirect('/login/')

def createThread(request, username):
	if request.POST:
		thread = Thread()
		thread.text = request.POST['thread']
		thread.author = User.objects.get(username=username)
		thread.save()
		return HttpResponseRedirect('/threads/')
	user = User.objects.get(username=username)
	return render(request, 'Threads/create.html', {'User' : user})

def comment(request,  id):
	thread = Thread.objects.get(id=id)
	if request.POST:
		user = User.objects.get(username=request.session['user'])
		com = Comment()
		com.text = request.POST['comment']
		com.author = user
		com.thread = thread
		com.save()
		return HttpResponseRedirect('.')
	comments = thread.comment_set.all()
	return render(request, 'Threads/comments.html', {'thread': thread, 'Comments' : comments})

Login/templates/Login/Login.html
<html lang="en">
<head>
  	<title>Login Form</title>
  	<style>
  	.my-block {
     	text-align: center;
      	display: table-cell;
        vertical-align: middle;
        color: orange;
        font-size: 32;
        font-weight: 100;
        font-style: oblique; 
        font-family: 'TImes New Roman';
    }
   	</style>
</head>
<body>
	<center>
  		<section class="my-block">
    		<div>
      			<h1>Login to Web App</h1>
      			<form method="post" action='{% url 'Login:Login' %}'>
      				{%csrf_token%}
      				<p style="font-size: 20; color:red">
      				{%if status == 1%}
      				*Invalid Username or Password
      				{%endif%}
      				{%if register == 1%}
      				Registered Successfully.
      				{%endif%}
      				</p>
        			<p><input type="text" name="username" value="" placeholder="Username"></p>
        			<p><input type="password" name="password" value="" placeholder="Password"></p>
        			<p><input type="submit" name="commit" value="Login"></p>
      			</form>
            <a href="{% url 'Login:Register' %}"><button>Register</button></a>
    		</div>
  		</section>
  	</center>
</body>
</html>

Login/templates/Login/Register.html
<html lang="en">
<head>
  	<title>Login Form</title>
  	<style>
  	.my-block {
     	text-align: center;
      	display: table-cell;
        vertical-align: middle;
        color: orange;
        font-size: 32;
        font-weight: 100;
        font-style: oblique; 
        font-family: 'TImes New Roman';
    }
   	</style>
</head>
<body>
	<center>
  		<section class="my-block">
    		<div>
      			<h1>Register to Web App</h1>
      			<form method="post" action='{% url 'Login:Register' %}'>
      				{%csrf_token%}
              <p style="font-size: 20; color:red">
              {%if fill == 1%}
              *Please Fill Form completely.
              {%endif%}
              </p>
        			<p><input type="text" name="fname" value="" placeholder="First name"></p>
              <p><input type="text" name="lname" value="" placeholder="Last name"></p>
              <p style="font-size: 20; color:red">
              {%if username == 1%}
              *Username already taken.
              {%endif%}
              </p>
              <p><input type="text" name="username" value="" placeholder="Username"></p>
        			<p><input type="password" name="password" value="" placeholder="Password"></p>
              <p style="font-size: 20; color:red">
              {%if email == 1%}
              *Email already registered.
              {%endif%}
              </p>
              <p><input type="email" name="email" value="" placeholder="Email"></p>
        			<p><input type="submit" name="commit" value="Register"></p>
      			</form>
            <a href=".."><button>Login</button></a>
    		</div>
  		</section>
  	</center>
</body>
</html>

Login/templates/Login/index.html
{{ User.first_name }}, You are successfully logged in.
<a href = 'logout'>Logout</a>

Login/templates/Threads/comments.html
<a href="{% url 'Threads:Home' %}">Home</a>
<a style="float:right" href="{% url 'Login:Logout' %}">Logout</a>
<h1>Thread</h1>
<p>
{{thread.text}} by {{thread.author}}
</p>

<h2>
Comments
</h2>
{% for comment in Comments %}
{{forloop.counter}}. {{comment.text}} by {{comment.author.username}}<br>
{% endfor %}

<form action='.' method="POST">
{% csrf_token %}
<input type="text" name="comment">
<input type="submit">
</form>

Login/templates/Threads/create.html
Hello, {{User.first_name}}<br>
<a href="..">Home</a>
<a style="float:right" href="{% url 'Login:Logout' %}">Logout</a>
<form action='.' method = "POST">
{% csrf_token %}
	<input type="text" name="thread">
	<input type="submit" value="Submit">
</form>

Login/templates/Threads/threads.html
Hello, {{User.first_name}} <p style>
<a href="{% url 'Threads:Create' User.username %}">Create Thread</a>
<a style="float:right" href="{% url 'Login:Logout' %}">Logout</a>
</p>
{% for thread in threadlist %}
{{forloop.counter}}. <a href="{% url 'Threads:Comment' thread.id %}">{{thread.text}}</a> by {{thread.author.username}}<br>
{% endfor %}